# -*- coding: utf-8 -*-
"""clean_data_script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W7V5qmj-xxnUE6q4EvMOMbIUEWuSpSAy
"""

import pandas as pd
import numpy as np

# 1. Load the messy data
try:
    df = pd.read_csv('Messy_EMEA_Supply_Chain_Data.csv')
    print(f"Original dataset shape: {df.shape}")
except FileNotFoundError:
    print("Error: Messy_EMEA_Supply_Chain_Data.csv not found in this folder.")
    exit()

# 2. Drop rows with critical null values (Carrier and Weight only!)
df = df.dropna(subset=['Carrier_3PL', 'Weight_kg'])
# Replace the blank claims with "No_Claim" so they aren't Null anymore
df['Claim_Status'] = df['Claim_Status'].fillna('No_Claim')

# 3. Clean categorical text data (Fixing manual entry typos)
df['Carrier_3PL'] = df['Carrier_3PL'].replace({
    'dhl express': 'DHL_Express',
    'DPD-Local ': 'DPD_Local',
    'DPD-Local': 'DPD_Local'
})
df['Origin_Location'] = df['Origin_Location'].replace({
    'London DC': 'DC_London_UK',
    'Frankfurt_Warehouse': 'DC_Frankfurt_DE'
})

# 4. Fix Impossible/Negative Values
# Take the absolute value to correct any billing system credit errors or negative distances
df['Freight_Spend_EUR'] = df['Freight_Spend_EUR'].abs()
df['Distance_km'] = df['Distance_km'].abs()

# 5. Standardize Date Formats
# Convert the messy mix of EU/US/ISO strings into standard datetime format
df['Order_Date'] = pd.to_datetime(df['Order_Date'], format='mixed', dayfirst=True)
df['Order_Date'] = df['Order_Date'].dt.strftime('%Y-%m-%d')

# 6. Remove exact duplicate rows
df = df.drop_duplicates()
print(f"Shape after dropping duplicates: {df.shape}")

# 7. Recalculate financial discrepancies
# This ensures total accuracy for your Tableau dashboard
df['Invoice_Discrepancy'] = (df['Invoice_Billed_EUR'] - df['Freight_Spend_EUR']).round(2)

# 8. Export the final, cleaned dataset
output_file = 'clean_shipments_final.csv'
df.to_csv(output_file, index=False)
print(f"\nData cleaning complete! Saved to {output_file}")