# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1phDHMv7A23OYWTnCo12GeU_uKpYTp7r4
"""

import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import random

# Set random seed for reproducibility
np.random.seed(42)

# Define network parameters
num_records = 50000
origins = ['DC_London_UK', 'DC_Frankfurt_DE', 'DC_Lyon_FR', 'Vendor_Rotterdam_NL', 'US_Home_Office_NY']
destinations = ['Store_London', 'Store_Paris', 'Store_Berlin', 'Store_Milan', 'Ecom_Customer_UK', 'Ecom_Customer_EU']
carriers = ['DHL_Express', 'XPO_Logistics', 'Maersk_Inland', 'DPD_Local', 'FedEx_Crossborder']
channels = ['Retail_Store', 'E_Commerce', 'B2B_Wholesale']
edi_status = ['Success', 'Success', 'Success', 'Failure_ASN_Missing', 'Failure_Invoice_Mismatch']
claim_types = ['None', 'None', 'None', 'Damaged_in_Transit', 'Lost_Freight', 'Shortage']

# 1. Generate clean base data
data = {
    'Shipment_ID': [f"SHP{str(100000 + i)}" for i in range(num_records)],
    'Order_Date': [datetime(2023, 1, 1) + timedelta(days=random.randint(0, 365)) for _ in range(num_records)],
    'Origin_Location': np.random.choice(origins, num_records),
    'Destination': np.random.choice(destinations, num_records),
    'Channel': np.random.choice(channels, num_records),
    'Carrier_3PL': np.random.choice(carriers, num_records),
    'Distance_km': np.random.randint(50, 2500, num_records),
    'Weight_kg': np.random.uniform(5.0, 5000.0, num_records),
}

df = pd.DataFrame(data)

# Calculate transit times and status
df['Expected_Transit_Days'] = np.where(df['Distance_km'] < 500, 1, np.where(df['Distance_km'] < 1000, 3, 5))
delay_factors = {'DHL_Express': 0, 'XPO_Logistics': 1, 'Maersk_Inland': 2, 'DPD_Local': 0, 'FedEx_Crossborder': 1}
df['Actual_Transit_Days'] = df['Expected_Transit_Days'] + np.random.choice([0, 0, 1, 2, 3], num_records)
df['Actual_Transit_Days'] = df.apply(lambda row: row['Actual_Transit_Days'] + delay_factors[row['Carrier_3PL']], axis=1)
df['Delivery_Status'] = np.where(df['Actual_Transit_Days'] <= df['Expected_Transit_Days'], 'On_Time', 'Late')

# Freight costs and billing
df['Freight_Spend_EUR'] = (df['Distance_km'] * 0.15) + (df['Weight_kg'] * 0.5) + np.random.randint(50, 200, num_records)
df['Invoice_Billed_EUR'] = df['Freight_Spend_EUR'] * np.random.choice([1.0, 1.0, 1.05, 1.10], num_records)
df['EDI_Compliance_Status'] = np.random.choice(edi_status, num_records)
df['Claim_Status'] = np.random.choice(claim_types, num_records)
df.loc[df['Delivery_Status'] == 'On_Time', 'Claim_Status'] = 'None'


# ==========================================
# 2. INTRODUCE "MESSY" DATA FOR PORTFOLIO
# ==========================================

# A. Insert Missing Values (Nulls)
# Drop carrier names for 5% of records
df.loc[df.sample(frac=0.05).index, 'Carrier_3PL'] = np.nan
# Drop weights for 3% of records
df.loc[df.sample(frac=0.03).index, 'Weight_kg'] = np.nan

# B. Inject Inconsistent Categorical Typos
# Mess up some origin and carrier names (simulates manual entry errors)
df['Carrier_3PL'] = df['Carrier_3PL'].replace({'DHL_Express': 'dhl express', 'DPD_Local': 'DPD-Local '})
df['Origin_Location'] = df['Origin_Location'].replace({'DC_London_UK': 'London DC', 'DC_Frankfurt_DE': 'Frankfurt_Warehouse'})

# C. Inject Impossible/Negative Values
# Make 2% of freight spend negative (simulating billing system credit errors)
df.loc[df.sample(frac=0.02).index, 'Freight_Spend_EUR'] *= -1
# Make 1% of distances negative
df.loc[df.sample(frac=0.01).index, 'Distance_km'] *= -1

# D. Mess Up Date Formats
# Convert standard dates into a mix of formats (EU vs US vs String)
def mess_up_date(date_val):
    rand = random.random()
    if rand < 0.33:
        return date_val.strftime('%d/%m/%Y')  # EU format
    elif rand < 0.66:
        return date_val.strftime('%Y-%m-%d')  # ISO format
    else:
        return date_val.strftime('%m-%d-%Y')  # US format

df['Order_Date'] = df['Order_Date'].apply(mess_up_date)

# E. Add Duplicate Records
# Duplicate 500 random rows (simulates double-scanned EDI shipments)
duplicates = df.sample(n=500)
df = pd.concat([df, duplicates], ignore_index=True)

# Round financials to 2 decimal places after messing them up
df['Freight_Spend_EUR'] = df['Freight_Spend_EUR'].round(2)
df['Invoice_Billed_EUR'] = df['Invoice_Billed_EUR'].round(2)
df['Invoice_Discrepancy'] = (df['Invoice_Billed_EUR'] - df['Freight_Spend_EUR']).round(2)

# Shuffle the dataset so duplicates and errors are spread out
df = df.sample(frac=1).reset_index(drop=True)

# Export to CSV
df.to_csv('Messy_EMEA_Supply_Chain_Data.csv', index=False)
print("Messy Dataset created successfully! Saved as Messy_EMEA_Supply_Chain_Data.csv")