# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Og5hRY2wepNtvTsgP0BXKTe24PmtvA2
"""

import pandas as pd
import numpy as np

# Set random seed so the results are exactly the same every time you run it
np.random.seed(42)

# Define dataset size
num_rows = 50000

# 1. Generate Distance_km (Uniform distribution between 15km and 2450km)
distance_km = np.random.uniform(low=15.0, high=2450.0, size=num_rows)

# 2. Generate Weight_kg (Normal distribution: Mean=150, Std=30)
weight_kg = np.random.normal(loc=150.0, scale=30.0, size=num_rows)

# Clip the minimum weight so the AI doesn't generate physically impossible negative weights
weight_kg = np.clip(weight_kg, a_min=22.50, a_max=None)

# 3. Build the DataFrame
df = pd.DataFrame({
    'Shipment_ID': range(1, num_rows + 1),
    'Distance_km': distance_km,
    'Weight_kg': weight_kg
})

# 4. Inject "Dirty Data": Randomly remove 1,500 weights to simulate missing EDI scans
missing_indices = np.random.choice(df.index, size=1500, replace=False)
df.loc[missing_indices, 'Weight_kg'] = np.nan

# 5. Output the validation statistics
print("Data Validation: df.describe()")
print("-" * 30)
print(df[['Weight_kg', 'Distance_km']].describe().round(2))